### ISSUE TITLE
Access Irp internal fields

### ISSUE THREAD

**Issue by lberezy** [seanyoung/cir#1]
It would be very useful to be able to access the results of `Irp` after parsing, particularly to get information like the carrier and modulation (`GeneralSpec`) ahead of time.

Currently, to do this I can create a `Message` and access that information there, but this requires passing in a `VarTable` that may not match the parsed spec.

Happy to add a PR, but wanted to ask if you had any thoughts on this first (is it okay to just make all the fields `pub` or are getters more appropriate)?

**Comment by seanyoung** [comment]
What are you trying to do with that information? Just curious what you are trying to build.

I think getters might be more appropriate, we may want to change the parsed data structure (like `GeneralSpec`) in the future. In fact `GeneralSpec` itself is no longer `pub` on latest `main` branch. 

PR is welcome :smiley:

**Comment by lberezy** [comment]
I just thought it was ergonomically awkward to have to create a message just to access information that was already parsed out. I'm imagining cases where it might be useful to operate over a library of many irp strings to categorize and filter things easily.
