### ISSUE TITLE
Parsing scancodes from `ir-keytable`?

### ISSUE THREAD

**Issue by TooTallNate** [seanyoung/cir#4]
Hi there! First off, thank you for this library! It's caused me to play around with Rust for the first time and I'm having fun. The pronto code parsing also helped me convert codes to raw IR format usable with `ir-ctl`, but now I'm trying to use `cir` directly to send codes.

My question is, I have a bunch of scancodes generated from `ir-keytable` already (e.g. `nec32:0x87e5fe2c`) and I'm wondering the proper way for those to be input into `cir`. Is this functionality implemented already or is it still TODO?

**Comment by seanyoung** [comment]
@TooTallNate thank you very much!

Unfortunately, this is still a TODO. Essentially what we need is IRP expressions for all the protocols like `nec32`, so that we can use `cir` for converting them to raw IR, and also decode them.

I'm currently working on the DFA decoder.

**Comment by seanyoung** [comment]
I have finally added support for this. The `cir transmit rawir` takes the same arguments as `ir-ctl` for sending (except for keymaps). So you can send like so:

```
cir transmit rawir -S nec32:0x87e5fe2c
```
Note: you need a recent version from git to make this work

**Comment by seanyoung** [comment]
Is that what you were after? @TooTallNate

**Comment by seanyoung** [comment]
Let me know if you need anything else
